[workspace]
resolver = "2"
members = [
  "nvbit-sys",
  "nvbit-rs",
  "nvbit-build",
  "nvbit-io",
  "nvbit-model",
  "examples/*"
]

[profile.dev]
opt-level = 0
debug = 1

[profile.release]
lto = true
