[package]
name = "nvbit-rs"
version = "0.0.4"
edition = "2021"
publish = true

description = "Idiomatic library for using the NVIDIA NVBIT binary instrumentation library"
authors = ["romnn <contact@romnn.com>"]
license-file = "LICENSE"
documentation = "https://docs.rs/nvbit-rs"
homepage = "https://github.com/romnn/nvbit-rs"
repository = "https://github.com/romnn/nvbit-rs"
categories = [
  "api-bindings",
  "development-tools::profiling",
  "os::unix-apis",
]
keywords = [
  "nvbit",
  "profiling",
  "gpgpu",
  "nvidia",
  "ffi",
]

[dependencies]
nvbit-sys = { path = "../nvbit-sys" }
cxx = "1.0"
thiserror = "1"
