[package]
name = "accelsim"
version = "0.1.0"
edition = "2021"

[lib]
# crate-type = ["staticlib"]
crate-type = ["cdylib", "staticlib"]
# crate-type = ["cdylib"]
# crate-type = ["staticlib", "cdylib"]

[dependencies]
nvbit-rs = { path = "../../nvbit-rs" }
lazy_static = "1"
libc = "0.2"
anyhow = "1.0"
# rustacuda = "0.1"
# rustacuda_derive = "0.1"
# rustacuda_core = "0.1"

# todo: remove
cxx = "1.0"
# libloading = "0.7"
nvbit-sys = { path = "../../nvbit-sys" }

[build-dependencies]
cc = "1"
bindgen = "0.61"
