[package]
name = "accelsim"
version = "0.1.0"
edition = "2021"

# [build]
# lto = true

[lib]
# crate-type = ["staticlib"]
crate-type = ["cdylib", "staticlib"]
# crate-type = ["cdylib"]
# crate-type = ["staticlib", "cdylib"]

[dependencies]
# todo: when ready, use nvbit-rs
nvbit-sys = { path = "../../nvbit-sys" }
lazy_static = "1"
libc = "0.2"
libloading = "0.7"
anyhow = "1.0"

[build-dependencies]
cc = "1"
