name: local

on: [push, pull_request]

jobs:
  local:
    name: local test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '11.7.0'
          method: network

      - run: |
          echo ${{steps.cuda-toolkit.outputs.CUDA_PATH}}
          sudo ldconfig ${{steps.cuda-toolkit.outputs.CUDA_PATH}}

      - name: Test
        run: cargo test --all-targets
