name: release
on:
  push:
    tags:
      - "*"
jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.10
        id: cuda-toolkit
        with:
          cuda: "11.8.0"
          method: "network"
          use-github-cache: true
          # list of available packages here:
          # https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/
          sub-packages: '["nvcc", "runtime", "profiler-api"]'
      - name: Publish crates
        uses: romnn/publish-crates@main
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          resolve-versions: true
          publish-delay: 30s
