name: test

on: [push, pull_request]

jobs:
  feature-matrix:
    uses: ./.github/workflows/feature-matrix.yml

  test:
    name: test (features ${{ matrix.features }})
    runs-on: ubuntu-latest
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.feature-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test
        run: >-
          cargo test
          --package "${{ matrix.package.package }}"
          --features "${{ matrix.package.features }}"
          --all-targets
