name: test

on: [push, pull_request]

jobs:
  feature-matrix:
    uses: ./.github/workflows/feature-matrix.yml

  test:
    name: test ${{ matrix.package.name }} (${{ matrix.package.features }})
    runs-on: ubuntu-latest
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.feature-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '11.7.0'
      - run: |
          sudo ldconfig
          sudo ldconfig -v

      - name: Test
        run: >-
          cargo test
          --package "${{ matrix.package.name }}"
          --features "${{ matrix.package.features }}"
          --all-targets
